[package]
name = "m3"
version = "0.1.0"
authors = ["ibaryshnikov <baryshnikov.il@gmail.com>"]

[dependencies]
log = "0.4"
web_logger = "0.1"
stdweb = "0.4.6"
yew = { git = "https://github.com/DenisKolodin/yew" }
rand = { version = "0.5.0", features = ["stdweb"] }
